In [3]:
import numpy as np
test_array = np.arange(1, 11)
test_array.sum()

55

In [4]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
test_array.sum(axis=0)

array([15, 18, 21, 24])

In [7]:
test_array.sum(axis=1)

array([10, 26, 42])

In [8]:
test_array = np.arange(1, 13).reshape(3, 4)
third_order_tensor = np.array([test_array, test_array, test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [9]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [10]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [11]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [12]:
test_array = np.arange(1, 13).reshape(3, 4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
test_array.mean(axis=1)

array([ 2.5,  6.5, 10.5])

In [18]:
test_array.std() 

3.452052529534663

In [15]:
test_array.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [16]:
np.sqrt(test_array)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [17]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
np.vstack((v1, v2))

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6])

In [20]:
v1 = v1.reshape(-1, 1)
v2 = v2.reshape(-1, 1)
v1

array([[1],
       [2],
       [3]])

In [21]:
v2

array([[4],
       [5],
       [6]])

In [22]:
np.hstack((v1,v2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [23]:
v1 = np.array([[1, 2, 3]])
v2 = np.array([[4, 5, 6]])
np.concatenate((v1,v2), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
v1 = np.array([1, 2, 3, 4]).reshape(2,2)
v2 = np.array([[5,6]]).T
v1

array([[1, 2],
       [3, 4]])

In [25]:
v2

array([[5],
       [6]])

In [26]:
np.concatenate((v1,v2), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [27]:
x = np.arange(1, 7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
x + x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [29]:
x - x

array([[0, 0, 0],
       [0, 0, 0]])

In [30]:
x / x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [31]:
x ** x

array([[    1,     4,    27],
       [  256,  3125, 46656]])

In [33]:
x_1 = np.arange(1, 7).reshape(2,3)
x_2 = np.arange(1, 7).reshape(3,2)
x_1

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
x_2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
x = np.arange(1, 10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
x + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [37]:
x - 2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [38]:
x // 3

array([[0, 0, 1],
       [1, 1, 2],
       [2, 2, 3]])

In [39]:
x ** 2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [41]:
x = np.arange(1, 13).reshape(4,3)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [42]:
v = np.arange(10 , 40 , 10)
v

array([10, 20, 30])

In [43]:
v = np.arange(10 , 40 , 10)
v

array([10, 20, 30])

In [44]:
x + v

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])