In [1]:
# 데이터 로드 (붓꽃 데이터)
from sklearn.datasets import load_iris
iris = load_iris()

In [2]:
X = iris.data # iris의 입력값 (꽃잎과 꽃받침의 길이와 넓이)
Y = iris.target # iris의 출력값 (종, versicolor, setosa, virginica)

type(X) # type() 데이터의 타입 출력 , numpy 데이터라고 출력 됨

numpy.ndarray

In [3]:
import numpy as np  # numpy 라이브러리를 사용할건데 그 이름 np라고 하겠다

np.shape(X) # 데이터 X의 shape(몇 행 몇 열인지?)을 출력 

(150, 4)

In [4]:
X[:5] # X의 앞에서 5개의 데이터 출력

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [5]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
import tensorflow as tf

#원 핫 인코딩 to_categorical(출력값)
Y = tf.keras.utils.to_categorical(Y)
Y[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [8]:
from sklearn.model_selection import train_test_split

# 데이터 분할 (입력값 X, 출력값 Y) -> (학습용 입력값 X, 테스트용 입력값 X, 학습용 출력값 Y, 테스트용 출력값 Y)
train_X, test_X, train_Y, test_Y = train_test_split(X, Y, test_size=0.2) # 학습용4 : 테스트용1로 분할

In [9]:
np.shape(train_X)

(120, 4)

In [10]:
np.shape(train_Y)

(120, 3)

In [11]:
# 모델링
# 뉴럴네트워크의 레이어를 순차적으로  쌓아 나감
# 입력층, 은닉층, 출력층을 순차적으로
# 4개의 입력값, 3개의 출력값 <-- 데이터 종속적
# 은닉층은 우리 마음대로 구성할 수 있는데, 이번에는 10개의 뉴런을 갖고 있는 레이어 1개를 만듬
model = tf.keras.models.Sequential([
                                    tf.keras.layers.Input(4),
                                    tf.keras.layers.Dense(10, activation='relu'),
                                    tf.keras.layers.Dense(3, activation='softmax') # softmax는 원핫인코딩된 출력값과 페어로 사용
])

In [12]:
# 모델 학습 방법 (compile)
# optimizer : 어떻게 뉴럴네트워크의 Weight와 bias를 학습할 것인지
# learning_rate : 얼만큼 값(weight, bias)들을 학습시킬 것인지
# loss : 오차를 측정하는 방법
# metric : 학습하는 동안 모델을 평가하는 방법

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.01), loss="categorical_crossentropy", metrics=["accuracy"])

In [ ]:
# 모델 학습 시작 (fit)
# 학습용 입력값(train_X), 학습용 출력값(train_Y)
# epochs : 얼만큼 데이터를 반복시켜서 학습 할 것인지 ex) 120개의 데이터 X 30 = 3600개의 데이터로 학습
# validation_data : 학습 중에 정확도를 측정하는 데이터

model.fit(train_X, train_Y, epochs=30, validation_data=(test_X, test_Y))

In [14]:
# 모델 테스트
# 0번째 꽃 종류의 실제 데이터 : [5.1, 3.5, 1.4, 0.2], [4.9, 3. , 1.4, 0.2]
# 테스트 데이터 [5, 3.4, 1.3, 0.15]
test = np.array([[5, 3.4, 1.3, 0.15]]) # numpy array 형태로 입력값을 정의

pred = model.predict(test)

print(pred) # 3개의 출력층 값이 출력
print(np.argmax(pred)) # 3개의 출력값 중 가장 큰 값의 번째를 출력

[[9.6784526e-01 3.2117516e-02 3.7301801e-05]]
0
